### ISSUE TITLE
Français HTML checklist not found

### ISSUE THREAD

**Issue by VickiLanger** [VickiLanger/OpenGates#33]
## Problem:
Currently, the `https://github.com/VickiLanger/OpenGates/blob/main/site/versions/1/checklist_fr.md` doesn't show up in HTML like the English version does. It throws a [404](http.cat/404). 
(side note: we also need a 404 page #28, but that's not part of this issue)

## Expected behavior
- [x] French checklist works in markdown. `https://raw.githubusercontent.com/VickiLanger/OpenGates/main/site/versions/1/checklist.md` should have a French counterpart `https://raw.githubusercontent.com/VickiLanger/OpenGates/main/site/versions/1/checklist_fr.md`
- [ ] French checklist exists in html. `https://opengates.dev/checklist/` should have a French counterpart `https://opengates.dev/checklist_fr/`
- [ ] Homepage links to French checklist. https://github.com/VickiLanger/OpenGates/blob/main/site/home.md should have `- [Français (HTML version)](https://vickilanger.github.io/OpenGates/checklist_fr/)` in it's "latest version of checklist" list 

---
*Don't forget to checkout [AntiGatekeep Checklist for Content Creation](https://vickilanger.github.io/OpenGates/) and follow the bot on [Twitter](TBD) to see the hard work you put in.*

**Comment by dassudip2001** [comment]
I am interested in fixing this issue.
